l_english:
 SETTINGS_PAGE_GRAPHICS:0 "Graphics"
 SETTINGS_PAGE_GAME:0 "Game"
 SETTINGS_PAGE_SYSTEM:0 "System"
 SETTINGS_PAGE_CONTROLS:0 "Controls"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Interface"
 SETTINGS_PAGE_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_SCREEN:0 "Screen"
 SETTINGS_CATEGORY_QUALITY:0 "Quality"
 OPTION_EASY:0 "Easy"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Hard"
 OPTION_NEVER:0 "Never"
 OPTION_MONTHLY:0 "Every month"
 OPTION_HALFYEAR:0 "Every half year"
 OPTION_YEARLY:0 "Every year"
 OPTION_FIVE_YEAR:0 "Every five years"
 OPTION_NO_AUTOSAVE:0 "Do not autosave"
 SETTINGS_CATEGORY_ACCOUNT:0 "Account"
 SETTINGS_CATEGORY_SYSTEM:0 "System"
 SETTINGS_CATEGORY_CONTROLS:0 "Controls"
 SETTINGS_CATEGORY_CAMERA:0 "Camera"
 SETTINGS_CATEGORY_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 RESTORE:0 "Restore"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "設定"
 REQUIRES_RESTART:0 "Requires restart"
 REQUIRE_RESTART_DESCRIPTION:0 "Some settings will not take effect until you restart the game."