l_english:
 SETTINGS_PAGE_GRAPHICS:0 "グラフィック"
 SETTINGS_PAGE_GAME:0 "ゲーム"
 SETTINGS_PAGE_SYSTEM:0 "システム"
 SETTINGS_PAGE_CONTROLS:0 "コントロール"
 SETTINGS_PAGE_EDITOR:0 "エディター"
 SETTINGS_PAGE_INTERFACE:0 "インターフェース"
 SETTINGS_PAGE_AUDIO:0 "オーディオ"
 SETTINGS_CATEGORY_SCREEN:0 "画面"
 SETTINGS_CATEGORY_QUALITY:0 "品質"
 OPTION_EASY:0 "簡単"
 OPTION_NORMAL:0 "普通"
 OPTION_HARD:0 "難しい"
 OPTION_NEVER:0 "Never"
 OPTION_MONTHLY:0 "毎月"
 OPTION_HALFYEAR:0 "半年毎"
 OPTION_YEARLY:0 "毎年"
 OPTION_FIVE_YEAR:0 "5年毎"
 OPTION_NO_AUTOSAVE:0 "オートセーブなし"
 SETTINGS_CATEGORY_ACCOUNT:0 "アカウント"
 SETTINGS_CATEGORY_SYSTEM:0 "システム"
 SETTINGS_CATEGORY_CONTROLS:0 "操作"
 SETTINGS_CATEGORY_CAMERA:0 "カメラ"
 SETTINGS_CATEGORY_AUDIO:0 "オーディオ"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 RESTORE:0 "元に戻す"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "設定"
 REQUIRES_RESTART:0 "再起動が必要"
 REQUIRE_RESTART_DESCRIPTION:0 "いくつかの設定変更は再起動後に反映します"