l_english:
 is_your_child_desc: "あなたの子供だ"
 is_your_close_family_desc: "あなたの家族だ"
 is_your_house_desc: "あなたの家の一員だ"
 landed_spouse_desc: "所領を持つ配偶者がいる"
 landed_heir_desc: "所領を持つ後継者である"
 has_many_good_relations_desc: "多くの友人がいる"
 has_many_bad_relations_desc: "ライバルに悩まされる"
 part_of_feud_desc: "確執の一端"
 high_diplomacy_desc: "高い外交能力を有している"
 high_martial_desc: "高い軍事能力を有している"
 high_stewardship_desc: "高い管理能力を有している"
 high_intrigue_desc: "高い策略能力を有している"
 high_learning_desc: "高い学識を有している"
 high_prowess_desc: "高い武勇を有している"
 high_education_desc: "高ランクの教育特性を有している"
 more_beautiful_desc: "後継者よりも美しい"
 more_smart_desc: "後継者よりも賢い"
 more_fit_desc: "後継者よりも適格"
 more_strong_desc: "後継者よりも強い"
 more_skillful_desc: "後継者よりも技巧が高い"
 has_nickname_desc: "異名を持っている"
 more_famous_desc: "後継者よりも有名"
 second_in_line_desc: "相続順位の第二位"
 higher_title_desc: "より高位の称号を有している"
 new_liege_desc: "新たな主君に支配されるだろう"
 new_top_liege_desc: "新たな最上位の主君が誕生するだろう"
 tall_claims_desc: "重要な請求権を有している"
 pressed_claims_desc: "確固たる請求権を有している"
 unpressed_claims_desc: "曖昧な請求権を有している"
 inheritance_line_desc: "相続の候補者"
 has_interesting_story_desc: "興味深いストーリーを持っている"
 child_of_destiny_desc: "運命の子である"
 virtues_interesting_desc: "美徳の特性を持っている"
 tourney_xp_desc: "経験豊富な[GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 reveler_xp_desc: "経験豊富な[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 mystic_xp_desc: "[GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]としての経験がある"
 hunter_xp_desc: "経験豊富な[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 blademaster_xp_desc: "経験豊富な[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 traveler_xp_desc: "経験豊富な[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 physician_xp_desc: "経験豊富な[GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 herbalist_xp_desc: "経験豊富な[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 loyal_interesting_desc: "[GetTrait('loyal').GetName( GetNullCharacter )]である"
 disloyal_interesting_desc: "[GetTrait('disloyal').GetName( GetNullCharacter )]である"
 faith_warrior_interesting_desc: "[GetTrait('faith_warrior').GetName( GetNullCharacter )]である"
 blood_of_prophet_interesting_desc: "[GetTrait('blood_of_prophet').GetName( GetNullCharacter )]を有している"
 varangian_interesting_desc: "[GetTrait('varangian').GetName( GetNullCharacter )]である"
 poet_interesting_desc: "[GetTrait('poet').GetName( GetNullCharacter )]である"
 peasant_leader_interesting_desc: "[GetTrait('peasant_leader').GetName( GetNullCharacter )]である"
 populist_leader_interesting_desc: "[GetTrait('populist_leader').GetName( GetNullCharacter )]である"
 berserker_interesting_desc: "[GetTrait('berserker').GetName( GetNullCharacter )]である"
 born_in_the_purple_interesting_desc: "[GetTrait('born_in_the_purple').GetName( GetNullCharacter )]である"
 scaly_interesting_desc: "[GetTrait('scaly').GetName( GetNullCharacter )]の肌を持っている"
 albino_interesting_desc: "[GetTrait('albino').GetName( GetNullCharacter )]である"
 dwarf_interesting_desc: "[GetTrait('dwarf').GetName( GetNullCharacter )]である"
 giant_interesting_desc: "[GetTrait('giant').GetName( GetNullCharacter )]である"
 devoted_interesting_desc: "[GetTrait('devoted').GetName( GetNullCharacter )]である"
 pure_blooded_interesting_desc: "Is [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "Is a [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "Is [GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc: "Is [GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc: "Is a Diarch"
 ruler_in_foreign_lands_interesting_desc: "Is a Ruler in Foreign Lands"
 valiant_knight_interesting_desc: "Is a Valiant Knight"
 sinful_bastard_interesting_desc: "Is a Sinful [GetTrait('bastard').GetName( GetNullCharacter )]"
 adventurer_interesting_desc: "Is an Adventurer"
 liege_crusader_king_liege_lineage_interesting_desc: "Liege of [GetTrait('crusader_king').GetName( GetNullCharacter )] Lineage"
 holy_site_steward_interesting_desc: "Capital is a Holy Site"
 has_a_legend_interesting_desc: "Has a Legend"
 weak_hook_liege_interesting_desc: "Has Weak Hook on Liege"
 strong_hook_liege_interesting_desc: "Has Strong Hook on Liege"
 beloved_by_pope_interesting_desc: "Beloved by the Pope"
 head_of_faith_interesting_desc: "Is a Head of Faith"
 stronger_than_liege_interesting_desc: "Stronger than Liege"
 small_king_interesting_desc: "Is a Small Kingdom Ruler"
 can_feudalize_interesting_desc: "Can Feudalize"
 multiduke_interesting_desc: "Holds many Duchies"
 legitimacy_interesting_desc: "Extremely Legitimate Ruler"
 non_dominant_gender_ambitious_char_interesting_desc: "Is an Ambitious Non-Dominant Gender Character"
 non_dominant_gender_ruler_interesting_desc: "Is a Non-Dominant Gender Ruler"
 treacherous_schemer_interesting_desc: "Is a Treacherous Schemer"
 kind_hearted_diplomat_interesting_desc: "Is a Kind-Hearted Diplomat"
 different_faith_interesting_desc: "Of Different Faith"
 greedy_steward_interesting_desc: "Is a Greedy Steward"
 brazen_commander_interesting_desc: "Is a Brazen Commander"
 pious_theologian_interesting_desc: "Is a Pious Theologian"
 salacious_seducer_interesting_desc: "Is a Salacious Seducer"
 high_skills_desc: "Skills are Very High"
 killed_a_lot_interesting_desc: "Killed Over 10 People"
 has_both_good_and_bad_genetics_desc: "Has Both Good and Bad Genetic Traits"
 good_genetics_desc: "Good Genetic Traits"
 bad_genetics_desc: "Bad Genetic Traits"
 holds_rome_interesting_desc: "Holds the [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Holds the [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Holds the [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Holds the [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Holds the [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Controls Special Buildings"
 has_historical_artifacts_interesting_desc: "所有する歴史的な宝物"
 underrepresented_faith_interesting_desc: "Is of an Underrepresented Faith"
 underrepresented_culture_interesting_desc: "Is of an Underrepresented Culture"
 outside_realm_desc: "Independent Ruler"
 knows_many_secrets_interesting_desc: "Knows Many Secrets"
 has_secrets_interesting_desc: "Has Secrets"
 extremely_wealthy_interesting_desc: "Very Wealthy"
 landless_heir_uninteresting_desc: "Unlanded Title Heir"
 three_virtues_desc: "Has Three Virtues"
 three_sins_desc: "Has Three Sins"
 skills_difficulty: "スキルから"
 legitimacy_difficulty: "正統性から"
 virtuous_traits_difficulty: "美徳の特性を持っている"
 physique_good_3_difficulty: "[GetTrait('physique_good_3').GetName( GetNullCharacter )]である"
 physique_good_2_difficulty: "[GetTrait('physique_good_2').GetName( GetNullCharacter )]である"
 physique_good_1_difficulty: "[GetTrait('physique_good_1').GetName( GetNullCharacter )]である"
 intellect_good_3_difficulty: "[GetTrait('intellect_good_3').GetName( GetNullCharacter )]である"
 intellect_good_2_difficulty: "[GetTrait('intellect_good_2').GetName( GetNullCharacter )]である"
 intellect_good_1_difficulty: "[GetTrait('intellect_good_1').GetName( GetNullCharacter )]である"
 beauty_good_3_difficulty: "[GetTrait('beauty_good_3').GetName( GetNullCharacter )]である"
 beauty_good_2_difficulty: "[GetTrait('beauty_good_2').GetName( GetNullCharacter )]である"
 beauty_good_1_difficulty: "[GetTrait('beauty_good_1').GetName( GetNullCharacter )]である"
 shrewd_difficulty: "[GetTrait('shrewd').GetName( GetNullCharacter )]である"
 strong_difficulty: "[GetTrait('strong').GetName( GetNullCharacter )]である"
 sinful_traits_difficulty: "罪深い特性を持っている"
 incapable_difficulty: "[GetTrait('incapable').GetName( GetNullCharacter )]である"
 leper_difficulty: "[GetTrait('leper').GetName( GetNullCharacter )]である"
 maimed_difficulty: "[GetTrait('maimed').GetName( GetNullCharacter )]である"
 inbred_difficulty: "[GetTrait('inbred').GetName( GetNullCharacter )]である"
 severely_wounded_difficulty: "重傷を負っている"
 disinherited_difficulty: "[GetTrait('disinherited').GetName( GetNullCharacter )]されている"
 sickly_difficulty: "[GetTrait('sickly').GetName( GetNullCharacter )]である"
 poxed_difficulty: "[GetTrait('great_pox').GetName( GetNullCharacter )]に罹っている"
 blind_difficulty: "[GetTrait('blind').GetName( GetNullCharacter )]である"
 infirm_difficulty: "[GetTrait('infirm').GetName( GetNullCharacter )]である"
 eunuch_difficulty: "[GetTrait('eunuch_1').GetName( GetNullCharacter )]である"
 lunatic_difficulty: "[GetTrait('lunatic').GetName( GetNullCharacter )]である"
 murderer_difficulty: "[GetTrait('murderer').GetName( GetNullCharacter )]である"
 excommunicated_difficulty: "破門されている"
 bleeder_difficulty: "[GetTrait('bleeder').GetName( GetNullCharacter )]に罹っている"
 physique_bad_3_difficulty: "[GetTrait('physique_bad_3').GetName( GetNullCharacter )]である"
 physique_bad_2_difficulty: "[GetTrait('physique_bad_2').GetName( GetNullCharacter )]である"
 physique_bad_1_difficulty: "[GetTrait('physique_bad_1').GetName( GetNullCharacter )]である"
 intellect_bad_3_difficulty: "[GetTrait('intellect_bad_3').GetName( GetNullCharacter )]である"
 intellect_bad_2_difficulty: "[GetTrait('intellect_bad_2').GetName( GetNullCharacter )]である"
 intellect_bad_1_difficulty: "[GetTrait('intellect_bad_1').GetName( GetNullCharacter )]である"
 beauty_bad_3_difficulty: "[GetTrait('beauty_bad_3').GetName( GetNullCharacter )]である"
 beauty_bad_2_difficulty: "[GetTrait('beauty_bad_2').GetName( GetNullCharacter )]である"
 beauty_bad_1_difficulty: "[GetTrait('beauty_bad_1').GetName( GetNullCharacter )]である"
 dull_difficulty: "[GetTrait('dull').GetName( GetNullCharacter )]である"
 weak_difficulty: "[GetTrait('weak').GetName( GetNullCharacter )]である"
 sodomite_difficulty: "[GetTrait('sodomite').GetName( GetNullCharacter )]である"
 incestuous_difficulty: "[GetTrait('incestuous').GetName( GetNullCharacter )]である"
 fornicator_difficulty: "[GetTrait('fornicator').GetName( GetNullCharacter )]である"
 adulterer_difficulty: "[GetTrait('adulterer').GetName( GetNullCharacter )]である"
 cannibal_difficulty: "[GetTrait('cannibal').GetName( GetNullCharacter )]である"
 witch_difficulty: "[GetTrait('witch').GetName( GetNullCharacter )]である"
 kinslayer_difficulty: "[GetTrait('kinslayer_1').GetName( GetNullCharacter )]である"
 flagellant_difficulty: "[GetTrait('flagellant').GetName( GetNullCharacter )]である"
 improvident_difficulty: "[GetTrait('improvident').GetName( GetNullCharacter )]である"
 profligate_difficulty: "Is [GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty: "Is [GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty: "Is a [GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty: "Is [GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty: "Is [GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty: "Is [GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty: "Is [GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty: "Is [GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty: "Has [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty: "Is [GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "Is [GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty: "Is [GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty: "Is [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "Is [GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty: "Is a [GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty: "Has Weak Heritage"
 comfort_eater_difficulty: "Is a [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "Is [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty: "Is [GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty: "Is [GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty: "Is [GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty: "Is a [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty: "Is [GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty: "Has [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 wounded_difficulty: "Is [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty: "Is an [GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty: "Has a [GetTrait('lisping').GetName( GetNullCharacter )] Impediment"
 stuttering_difficulty: "Has a [GetTrait('stuttering').GetName( GetNullCharacter )] Impediment"
 giant_difficulty: "Is a [GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty: "Has [GetTrait('scaly').GetName( GetNullCharacter )] Skin"
 clubfooted_difficulty: "Is [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty: "Is a [GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty: "Is [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty: "Is [GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "Is [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty: "Is a [GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty: "At War"
 losing_war_difficulty: "Losing Wars"
 faction_difficulty: "Targeted by Powerful Factions"
 powerful_neighbors_difficulty: "Powerful Neighboring Rulers"
 military_difficulty: "軍事力"
 rivals_difficulty: "Has Rivals"
 primary_heir_wrong_dynasty_difficulty: "Primary Heir from Wrong Dynasty"
 children_wrong_dynasty_difficulty: "Children are of the Wrong Dynasty"
 hostile_faith_liege_difficulty: "Liege of Hostile Faith"
 nonpreferred_gender_difficulty: "Non-Preferred Gender in Faith"
 wrong_lineality_difficulty: "Wrong Lineality in Marriage"
 stress_level_difficulty: "High Stress Level"
 gold_difficulty: "Excessive Wealth"
 debt_level_difficulty: "High Debt Level"
 is_ill_difficulty: "衰弱に苦しんでいる"
 imprisoned_difficulty: "投獄された"
 elder_difficulty: "高齢"
 poor_health_difficulty: "体調不良"
 is_a_vassal_difficulty: "封臣である"
 non_adult_difficulty: "子供"
 weak_domain_difficulty: "弱体の直轄領"
 unlanded_difficulty: "称号を保有していない"
 character_difficulty_text: "難易度:[Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "難易度の内訳"
 choose_destiny_header_text: "新たな運命を選ぶ"
 will_become_adventurer: "[GetGovernment('landless_adventurer_government').GetName]になるだろう"
 character_interest_breakdown_header: "興味深い観点"
 different_government_desc: "難易度の高い政体である"
 opposite_struggle_faction_desc: "闘争における対立派閥"