l_english:
 SETTING_AUTOSAVE:0 "オートセーブ間隔"
 SETTING_DEBUG_SAVES:0 "デバッグセーブ数"
 SETTING_TUTORIAL:0 "チュートリアル"
 SETTING_DISABLED_HINTS:0 "ヒントを無効化"
 SETTING_FOCUS_ON_COMBAT:0 "戦闘を重視する"
 SETTING_TOOLTIP_DELAY:1 "ツールチップの遅延"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nツールチップが表示されるまでの時間を設定します。"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "アンロック遅延"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nツールチップがアンロックされるまでの時間を設定します。"
 SETTING_TOOLTIP_LOCK_TIME:0 "ロック遅延"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nツールチップがロックされるまでの時間を設定します。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "オープン時のロック遅延"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n別のツールチップが既に開いている時に、ツールチップがロックされるまでの時間を設定します。"
 SETTING_Sound_Effects:1 "全ての音響効果"
 SETTING_Sound_Effects_TOOLTIP:1 "#T 音響効果の音量\n#!すべての音響効果の音量を設定します。"
 SETTING_Ambience:0 "環境音"
 SETTING_Ambience_TOOLTIP:1 "#T 環境音の音量\n#!環境音の音量を設定します。"
 SETTING_TOOLTIP_MODE:1 "ツールチップモード"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nツールチップの「ロックイン」方法を設定し、解説の中の解説を可能にします。"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "マウステンデンシー"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nカーソルが離れるまで自動的にツールチップが固定されます。"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "アクションロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n#V ホイールクリック#!でツールチップの固定・固定解除を行います。"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "タイマーロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nカーソルをしばらく動かさずにいると、ツールチップがその場所に固定されます。#weak （初期設定）#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Misc"
 SETTINGS_CATEGORY_TOOLTIPS:0 "ツールチップ"
 SETTINGS_CATEGORY_SFX:0 "特別な音響効果"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "一般"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "マップコントロール"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "セーブゲーム"
 SETTINGS_CATEGORY_LANGUAGE:0 "言語"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "高度"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "ポートレート"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "病気や怪我をグラフィックに反映する"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n病気や怪我のグラフィックをキャラクターのポートレートに表示するかどうかを設定します。"
 NEVER:0 "なし"
 MONTHLY:0 "毎月"
 HALFYEAR:0 "半年毎"
 YEARLY:0 "毎年"
 FIVE_YEAR:0 "5年毎"
 SETTINGS_CATEGORY_TUTORIAL:0 "チュートリアル"
 SETTING_REACTIVE_TUTORIAL:1 "反応的なアドバイスを表示"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nゲーム中にチュートリアルを表示するかどうかを設定します。クルセイダーキングスIIIを初めてプレイする方におすすめです。"
 SETTING_SHOW_SUGGESTIONS:0 "提案を表示"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nゲーム中、定期的に行うべきことを提案するかどうかを設定します。クルセイダーキングスIIIを初めてプレイする方におすすめです。"
 RESET_REACTIVE_ADVICE:0 "反応的なアドバイスをリセット"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T 反応的なアドバイスをリセット#!\n既に表示された反応的なアドバイスがもう一度表示されます。"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "反応的なアドバイスをリセット"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "反動的なアドバイスをリセットしてよろしいですか？"
 SETTING_ADVANCED_SHADERS:0 "高度なシェーダー効果"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T 高度なシェーダー効果\n#!このオプションは高度なシェーダー効果を有効にします\n\nオフにするとパフォーマンスが向上する場合がありますが、地形や水等の質感が悪くなります"
 BASED_ON_ZOOM_LEVEL:0 "動的"
 ALWAYS_HIDE:0 "常に隠す"
 ALWAYS_SHOW:0 "常に表示"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "沿岸部の境界"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nこのオプションは、沿岸領域の境界線をいつ表示するかを制御します。\n$BASED_ON_ZOOM_LEVEL$の場合は、精細ズームレベルでは非表示になります。\n\n$ALWAYS_SHOW$や$ALWAYS_HIDE$を選択すると、沿岸領域の境界線が動的に隠れなくなる代わりに、パフォーマンスが向上する可能性があります。"
 SETTING_SHOW_NUDITY:0 "裸を表示"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\n人物の裸を表示するかどうかを設定します。"