l_english:
 SETTING_AUTOSAVE:0 "オートセーブ間隔"
 SETTING_DEBUG_SAVES:0 "デバッグセーブ数"
 SETTING_TUTORIAL:0 "チュートリアル"
 SETTING_DISABLED_HINTS:0 "ヒントを無効化"
 SETTING_FOCUS_ON_COMBAT:0 "Focus on combat"
 SETTING_REALM_BORDERS_AGAINST_WATER:0 "Realm Borders on Coasts"
 SETTING_TOOLTIP_DELAY:1 "ツールチップの遅延"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before tooltips appear."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "アンロック遅延"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "ロック遅延"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTING_Sound_Effects:1 "全ての音響効果"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Sound Effects Volume\n#!Sets the volume of ALL sound effects."
 SETTING_Ambience:0 "環境音"
 SETTING_Ambience_TOOLTIP:1 "#T Ambience Volume\n#!Sets the volume of environmental ambience."
 SETTING_TOOLTIP_MODE:1 "ツールチップモード"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nSets the way tooltips \"lock in,\" enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "マウステンデンシー"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nカーソルが離れるまで自動的にツールチップが固定されます。"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "アクションロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n#V ホイールクリック#!でツールチップの固定・固定解除を行います。"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "タイマーロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nカーソルをしばらく動かさずにいると、ツールチップがその場所に固定されます。#weak （初期設定）#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Misc"
 SETTINGS_CATEGORY_TOOLTIPS:0 "ツールチップ"
 SETTINGS_CATEGORY_SFX:0 "特別な音響効果"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "一般"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Map Controls"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "セーブゲーム"
 SETTINGS_CATEGORY_LANGUAGE:0 "言語"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "高度"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "ポートレート"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "病気や怪我をグラフィックに反映する"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n病気や怪我のグラフィックをキャラクターのポートレートに表示するかどうかを設定します。"
 NEVER:0 "なし"
 MONTHLY:0 "毎月"
 HALFYEAR:0 "半年毎"
 YEARLY:0 "毎年"
 FIVE_YEAR:0 "5年毎"
 SETTINGS_CATEGORY_TUTORIAL:0 "チュートリアル"
 SETTING_REACTIVE_TUTORIAL:1 "反応的なアドバイスを表示"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nゲーム中にチュートリアルを表示するかどうかを設定します。Crusader Kings IIIを初めてプレイする方におすすめです。"
 SETTING_SHOW_SUGGESTIONS:0 "提案を表示"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nゲーム中行うべきことを定期的に提案するかどうかを設定します。Crusader Kings IIIを初めてプレイする方におすすめです。"
 RESET_REACTIVE_ADVICE:0 "反応的なアドバイスをリセット"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T 反応的なアドバイスをリセット#!\n既に表示された反応的なアドバイスがもう一度表示されます。"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "反応的なアドバイスをリセット"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "反動的なアドバイスをリセットしてよろしいですか？"
 SETTING_ADVANCED_SHADERS:0 "高度なシェーダー効果"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T 高度なシェーダー効果\n#!このオプションは高度なシェーダー効果を有効にします\n\nオフにするとパフォーマンスが向上する場合がありますが、地形や水等の質感が悪くなります"
 BASED_ON_ZOOM_LEVEL:0 "Dynamic"
 ALWAYS_HIDE:0 "常に隠す"
 ALWAYS_SHOW:0 "常に表示"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "沿岸部の境界"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nThis option will control when coastal realm borders should be shown.\nIf $BASED_ON_ZOOM_LEVEL$ then they will be hidden in the detail zoom level.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."