l_english:
 MESSAGE_SETTINGS_WINDOW_NAME: "通知設定"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\n通知の頻度と表示形式をフィルター付きグループごとに設定します。"
 MESSAGE_SETTINGS_WINDOW_RESET: "デフォルトにリセット"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T 通知設定のリセット#!\n#I クリックで現在の変更をデフォルト設定にリセット#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "変更を適用"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I クリックで通知設定画面を閉じ、現在の変更を保存#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! フィード"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! トースト"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! ポップアップ"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! 通知しない"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "フィルター付きグループ"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "フィルター付きグループの名称"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "表示方式"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "フィルター付きグループの通知の表示方式"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "一時停止"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "このフィルターの通知が表示される際にゲームを一時停止"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T 自動停止の切り替え#!\n#I このフィルターの通知が表示される際にゲームを一時停止するかどうかの切り替え#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T 通知の無視#!\n#I クリックで現在の通知を無視し、キューにある次のメッセージを表示#!"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I クリックで通知設定を表示#!"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$#weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "カスタムメッセージ"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T カスタムメッセージ#!\n#I クリックして自分宛てにカスタムメッセージを書き、いつ受け取るかを選択する#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "到着日:[DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "見出し:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "本文:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "破棄"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T メッセージを破棄#!\n#I クリックで直近のメッセージを破棄#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "送信"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T 送信#!\n#I クリックで直近のメッセージを送信#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "日"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "月"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "年"
 message_settings_tab_settings: "設定"
 message_settings_tab_log: "メッセージログ"