l_english:
 MESSAGE_SETTINGS_WINDOW_NAME: "通知設定"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\n通知の頻度と表示形式をフィルター付きグループごとに設定します。"
 MESSAGE_SETTINGS_WINDOW_RESET: "デフォルトにリセット"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T 通知設定のリセット#!\n#I クリックで現在の変更をデフォルト設定にリセット#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "変更を適用"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I クリックで通知設定画面を閉じ、現在の変更を保存#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! フィード"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! トースト"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! ポップアップ"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! 通知しない"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "フィルター付きグループ"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "フィルター付きグループの名称"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "表示方式"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "フィルター付きグループの通知の表示方式"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "一時停止"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "このフィルターの通知が表示される際にゲームを一時停止"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T 自動停止の切り替え#!\n#I このフィルターの通知が表示される際にゲームを一時停止するかどうかの切り替え#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T 通知の無視#!\n#I クリックで現在の通知を無視し、キューにある次のメッセージを表示#!"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Click to open Message Settings#!"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Custom Message"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Custom Message#!\n#I Click to write a custom message to yourself and select when you want to receive it#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Arrival Date: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Title:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Description:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Discard"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Discard Message#!\n#I Click to discard current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Send"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Send#!\n#I Click to send current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Day"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Month"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Year"