l_english:
 SETTING_REFRACTION:0 "反射"
 SETTING_REFRACTION_QUALITY:0 "反射の品質"
 SETTING_MAPOBJECT_QUALITY:0 "マップオブジェクト"
 SETTING_MAP_SSAO:0 "マップのSSAO"
 SETTING_DOF:0 "被写界深度"
 SETTING_LENS_FLARE: "レンズフレア"
 SETTING_SECONDARY_LENS_FLARE: "Secondary lens flare"