l_english:
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$秒"
 SETTING_RENDERER:0 "描画エンジン"
 SETTING_VSYNC:0 "垂直同期"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!ゲームとあなたのモニターとのFPS値を合わせることにより、画面の乱れ（ティアリング）を減らします。\n\nこれをオフにするとパフォーマンスが改善されるかもしれません。"
 SETTING_MULTI_SAMPLING:0 "アンチエイリアス(MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!マルチサンプル・アンチエイリアス(MSAA)は作画の端をなめらかにします。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。"
 SETTING_ANISOTROPIC_FILTERING:0 "テクスチャフィルタリング"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!異方性フィルタリングを使用するとテクスチャ表面の見栄えが良くなります。\n\n設定を低くするとパフォーマンスが向上するかもしれません。"
 SETTING_FULLSCREEN_RESOLUTION:0 "解像度"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:2 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!ゲームの画像品質を設定します。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。"
 SETTING_WINDOWED_RESOLUTION:0 "ウィンドウ時の解像度"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "ゲームの解像度です。解像度が高いほど負荷がかかります。"
 SETTING_DISPLAY:0 "モニター"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!複数のモニターを使用している場合、使用するモニターを選択してください。"
 SETTING_GRAPHICS_DEVICE:0 "グラフィックカード"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!どのグラフィックカードをゲーム内で使うかを選択します。\n\n統合されたグラフィックカードやソフトウェアレンダリング機器を使用するとパフォーマンスが低下する可能性があります。"
 SETTING_SHADOW_MAP_RESOLUTION:0 "影の品質"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!影の設定が有効な場合においてマップ上に作画される影の解像度を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_DISPLAY_MODE:0 "ディスプレイモード"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!どのようにゲームを画面に表示するかを決定します。"
 SETTING_BLOOM:0 "ブルーム"
 SETTING_MESH_LOD_BIAS:0 "メッシュLOD品質"
 SETTING_MESH_LOD_FADE:0 "メッシュLODフェード"
 SETTING_TERRAIN_SMOOTHING:1 "地形の滑らかさ"
 OPTION_FULLSCREEN:0 "フルスクリーン"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!画面全体を使ってゲームを表示します。解像度設定は映像の精細さに関係します。"
 OPTION_WINDOWED:0 "ウィンドウ"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!ウィンドウにゲームを表示します。解像度設定はウィンドウ自体の大きさに関係します。"
 OPTION_DISABLED:1 "無効"
 OPTION_OFF:0 "オフ"
 OPTION_LOW:0 "低い"
 OPTION_MEDIUM:0 "中"
 OPTION_HIGH:0 "高い"
 OPTION_ULTRA:1 "ウルトラ"
 OPTION_CUSTOM:0 "カスタム"
 OPTION_DEFAULT:1 "デフォルト"
 SETTINGS_CATEGORY_UI:0 "インターフェイス"
 SETTINGS_CATEGORY_GAME:0 "ゲーム"
 SETTING_TEXTURE_QUALITY:1 "テクスチャ品質"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\n読み込まれるテクスチャの解像度を選択します。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。"
 SETTING_QUALITY:0 "品質プリセット"
 SETTING_SFX:0 "特殊効果"
 SETTING_UI:0 "インターフェイス"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!以下から高度なグラフィック設定のプリセットを選択して下さい。\n\n低い品質のプリセットはパフォーマンスを向上させます。"
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!「ブルーム」効果を有効にすることで、非常に強い光源は他の物体にまで光を及ぼすようになります。\n\nこれを無効にするとパフォーマンスが向上するでしょう。"
 SETTING_REFRACTION_TOOLTIP:0 "水面の反射を描写するかどうかを決定します。"
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\n水の反射を描写する場合の品質を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nマップ上の建物をはじめとする物体の品質の上限を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nユニットモデルをはじめとするマップ上の物体に関するLOD(作画の詳細さの度合い)の品質を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!これを有効にすると、ズームインやズームアウトをした際なめらかに3Dモデルの作画の詳細さの度合い(LOD)が変化します。\n\nこれを無効にするとパフォーマンスが向上するかもしれません。"
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "どのように都市やプロヴィンスの名前がマップ上に表示されるかを決定します。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "マップ上での国境線に通行不可能な地形が含まれるかどうかを決定します。"
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nユーザーインターフェイスの言語を決定します。"
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "あなたのパラドックスアカウントのメールアドレス"
 SETTING_ANIMATION_SPEED:0 "アニメーション速度"
 SETTING_GUI_SCALING:0 "GUIスケール"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!ユーザーインターフェイス全体の大きさを設定します。高解像度のモニターに対して有用です。\n\n#X この設定をあまりに高くするとインターフェイスが正常に画面内へ収まらなくなります！#!"
 SETTING_MOUSE_PANNING:0 "スクリーン端でのスクロール"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!マウスカーソルが画面やウィンドウの端に来たときにマップをスクロールさせるかどうかを設定します。"
 SETTING_SCROLL_SPEED:0 "スクロール速度"
 SETTING_CAMERA_ROTATION_SPEED:0 "カメラの回転速度"
 SETTING_ZOOM_SPEED:0 "ズーム速度"
 SETTING_INPUT_DEVICE:0 "入力デバイス"
 SETTING_EDITOR:0 "エディタ"
 SETTING_EDITOR_POSTFIX:0 "エディタポストフィックス"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "エディタを開くコマンド"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "ログを見るコマンド"
 SETTING_GRACEFUL_EXIT:0 "正式な退出"
 SETTING_LANGUAGE:0 "言語"
 MOUSE_AND_KEYBOARD:0 "マウスとキーボード"
 GAMEPAD:0 "ゲームパッド"
 SETTING_MULTISAMPLING_DISABLED:0 "無効"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "無効"
 SETTING_CAMERA_TILT:0 "カメラの傾き"
 SETTING_CAMERA_STRATEGY:0 "カメラタイプ"
 SETTING_CENTERED_ZOOM_IN:0 "画面中央へズームイン"
 SETTING_CAMERA_SPEED:0 "カメラ速度"
 CAMERA_TABLETOP:0 "テーブルトップ"
 CAMERA_FPS:0 "一人称"
 CAMERA_WASD:0 "WASD式"
 SETTING_Music:0 "音楽"
 SETTING_Ambient:0 "環境音"
 SETTING_Effects:0 "効果音"
 SETTING_Master:0 "全体"
 SETTING_Master_TOOLTIP:0 "#T 全体の音量\n#!ゲーム全体の音量を設定します。"
 SETTING_Music_TOOLTIP:0 "#T 音楽の音量\n#!音楽の音量を設定します。"
 SETTING_Ambient_TOOLTIP:0 "#T 環境音の音量\n#!環境音の音量を設定します。"
 SETTING_SFX_TOOLTIP:0 "#T 効果音の音量\n#!戦闘をはじめとする効果音の音量を設定します。"
 SETTING_UI_TOOLTIP:0 "#T インターフェイスの音量\n#!ユーザーインターフェイスの音量を設定します。"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!どのくらいの頻度でゲームを自動セーブするかを設定します。"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "オートセーブをクラウドに保存するかどうかを決定します。"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "カメラを常に北に向けるかどうかを決定します。"
 NO_AUTOSAVE:0 "オートセーブなし"
 SETTING_ANTI_ALIASING:0 "アンチエイリアス"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!アンチエイリアスは画像の端をなめらかにします。\n\nFXAAを推奨します。"
 OPTION_ANTI_ALIASING_DISABLED:0 "無効"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_FRAMERATE_CAP:1 "最大FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nゲームがレンダリングする最大のFPS（フレーム/秒）です。\n\n設定値を下げると消費パワーが軽減されるかもしれません。"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "デバッグログレベル"