l_english:
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X  $VALUE|%0$ 以上の値にスケール値を設定すると、画面外にインターフェースがはみ出てしまうかもしれません #!"
 RECOMMENDED_GUI_SCALE:1 "$VALUE|%0$ 以上の値にスケール値を設定すると、画面外にインターフェースがはみ出てしまうかもしれません"