l_english:
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$秒"
 SETTING_RENDERER:0 "描画エンジン"
 SETTING_VSYNC:0 "垂直同期"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!ゲームとあなたのモニターとのFPS値を合わせることにより、画面の乱れ（ティアリング）を減らします。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_MULTI_SAMPLING:0 "アンチエイリアス（MSAA）"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!マルチサンプル・アンチエイリアス(MSAA)は作画の端をなめらかにします。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。"
 SETTING_ANISOTROPIC_FILTERING:0 "テクスチャフィルタリング"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!異方性フィルタリングを使用するとテクスチャ表面の見栄えが良くなります。\n\n設定を低くするとパフォーマンスが向上するかもしれません。"
 SETTING_FULLSCREEN_RESOLUTION:0 "解像度"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!ゲームの画像品質を設定します。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。\n\n#X サポートされていないアスペクト比のゲーム解像度では、画面外にインターフェースがはみ出してしまうかもしれません#!"
 SETTING_WINDOWED_RESOLUTION:0 "ウィンドウ化時の解像度"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!ウィンドウモードの際のゲームの解像度を設定します。\n\n指定のフォーマット#b 数値#!x#b 数値#!でなければなりません。\n\n#X サポートされていないアスペクト比のゲーム解像度では、画面外にインターフェースがはみ出してしまうかもしれません#!"
 SETTING_DISPLAY:0 "モニター"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!複数のモニターを使用している場合、使用するモニターを選択してください。"
 SETTING_GRAPHICS_DEVICE:0 "グラフィックカード"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!どのグラフィックカードをゲーム内で使うかを選択します。\n\n統合されたグラフィックカードやソフトウェアレンダリング機器を使用するとパフォーマンスが低下する可能性があります。"
 SETTING_SHADOW_MAP_RESOLUTION:0 "影の品質"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!影の設定が有効な場合においてマップ上に作画される影の解像度を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_DISPLAY_MODE:0 "ディスプレイモード"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!どのようにゲームを画面に表示するかを決定します。"
 SETTING_BLOOM:0 "ブルーム"
 SETTING_MESH_LOD_BIAS:0 "メッシュLOD品質"
 SETTING_MESH_LOD_FADE:0 "メッシュLODフェード"
 SETTING_TERRAIN_SMOOTHING:1 "地形の滑らかさ"
 OPTION_FULLSCREEN:0 "フルスクリーン"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!画面全体を使ってゲームを表示します。解像度設定は映像の精細さに関係します。"
 OPTION_WINDOWED:0 "ウィンドウ化"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!ウィンドウにゲームを表示します。解像度設定はウィンドウ自体の大きさに関係します。"
 OPTION_DISABLED:1 "無効"
 OPTION_OFF:0 "オフ"
 OPTION_LOW:0 "低い"
 OPTION_MEDIUM:0 "中"
 OPTION_HIGH:0 "高い"
 OPTION_ULTRA:1 "ウルトラ"
 OPTION_CUSTOM:0 "カスタム"
 OPTION_DEFAULT:1 "デフォルト"
 SETTINGS_CATEGORY_UI:0 "インターフェイス"
 SETTINGS_CATEGORY_GAME:0 "ゲーム"
 SETTING_TEXTURE_QUALITY:1 "テクスチャ品質"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\n読み込まれるテクスチャの解像度を選択します。\n\n設定を低くするとパフォーマンスが改善されるかもしれません。"
 SETTING_QUALITY:0 "品質プリセット"
 SETTING_SFX:0 "特殊効果"
 SETTING_UI:0 "インターフェイス"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!以下から高度なグラフィック設定のプリセットを選択して下さい。\n\n低い品質のプリセットはパフォーマンスを向上させます。"
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!「ブルーム」効果を有効にすることで、非常に強い光源は他の物体にまで光を及ぼすようになります。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_REFRACTION_TOOLTIP:0 "水面の反射を描写するかどうかを決定します。"
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\n水の反射を描写する場合の品質を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nマップ上の建物をはじめとする物体の品質の上限を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nユニットモデルをはじめとするマップ上の物体に関するLOD(作画の詳細さの度合い)の品質を決定します。\n\n設定を低くするとパフォーマンスが向上することがあります。"
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!これを有効にすると、ズームインやズームアウトをした際なめらかに3Dモデルの作画の詳細さの度合い(LOD)が変化します。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "どのように都市やプロヴィンスの名前がマップ上に表示されるかを決定します。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "マップ上での国境線に通行不可能な地形が含まれるかどうかを決定します。"
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nユーザーインターフェイスの言語を決定します。"
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "あなたのパラドックスアカウントのメールアドレス"
 SETTING_ANIMATION_SPEED:0 "アニメーション速度"
 SETTING_GUI_SCALING:0 "GUIスケール"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!ユーザーインターフェイス全体の大きさを設定します。高解像度のモニターに対して有用です。\n\n#X この設定をあまりに高くするとインターフェイスが正常に画面内へ収まらなくなります！#!"
 SETTING_SCROLL_SPEED:1 "スクロール速度"
 SETTING_CAMERA_ROTATION_SPEED:1 "カメラの回転速度"
 SETTING_ZOOM_SPEED:1 "ズーム速度"
 SETTING_INPUT_DEVICE:0 "入力デバイス"
 SETTING_EDITOR:0 "エディタ"
 SETTING_EDITOR_POSTFIX:0 "エディタポストフィックス"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "エディタを開くコマンド"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "ログを見るコマンド"
 SETTING_GRACEFUL_EXIT:0 "正式な退出"
 SETTING_LANGUAGE:0 "言語"
 MOUSE_AND_KEYBOARD:0 "マウスとキーボード"
 GAMEPAD:0 "ゲームパッド"
 SETTING_MULTISAMPLING_DISABLED:0 "無効"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "無効"
 SETTING_CAMERA_TILT:0 "カメラの傾き"
 SETTING_CAMERA_STRATEGY:0 "カメラタイプ"
 SETTING_CENTERED_ZOOM_IN:0 "画面中央へズームイン"
 SETTING_CAMERA_SPEED:0 "カメラ速度"
 CAMERA_TABLETOP:0 "テーブルトップ"
 CAMERA_FPS:0 "一人称"
 CAMERA_WASD:0 "WASD式"
 SETTING_Music:0 "音楽"
 SETTING_Ambient:0 "環境音"
 SETTING_Effects:0 "効果音"
 SETTING_Master:0 "全体"
 SETTING_Master_TOOLTIP:0 "#T 全体の音量\n#!ゲーム全体の音量を設定します。"
 SETTING_Music_TOOLTIP:0 "#T 音楽の音量\n#!音楽の音量を設定します。"
 SETTING_Ambient_TOOLTIP:0 "#T 環境音の音量\n#!環境音の音量を設定します。"
 SETTING_SFX_TOOLTIP:0 "#T 効果音の音量\n#!戦闘をはじめとする効果音の音量を設定します。"
 SETTING_UI_TOOLTIP:0 "#T インターフェイスの音量\n#!ユーザーインターフェイスの音量を設定します。"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!どのくらいの頻度でゲームを自動セーブするかを設定します。"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "オートセーブをクラウドに保存するかどうかを決定します。"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "カメラを常に北に向けるかどうかを決定します。"
 NO_AUTOSAVE:0 "オートセーブなし"
 SETTING_ANTI_ALIASING:0 "アンチエイリアス"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!アンチエイリアスは画像の端をなめらかにします。\n\nFXAAを推奨します。"
 OPTION_ANTI_ALIASING_DISABLED:0 "無効"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_FRAMERATE_CAP:1 "最大FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nゲームがレンダリングする最大のFPS（フレーム/秒）です。\n\n設定値を下げると消費パワーが軽減されるかもしれません。"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "デバッグログレベル"
 SETTING_VALUE_MINUTES:0 "$VALUE$分"
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "ポートレートマルチサンプリング"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!「Alpha to Coverage」にマルチサンプルを使用して、髪をより滑らかにできます。\n\n低い設定にするとパフォーマンスが向上します。"
 SETTING_RENDER_SCALE:0 "描画スケール"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nユーザーインターフェイスを除く、メイン解像度に対するゲームのレンダリング解像度のスケールです。\n\n設定を低くするとパフォーマンスは向上しますが、全体的な忠実度は低下します。100％を超えると、忠実度は向上しますが、パフォーマンスが低下する可能性があります。"
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!カメラレンズをシミュレートするため被写界深度を有効にし、焦点から外れた部分へぼかし効果を与えます。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!スクリーンスペース・アンビエント・オクルージョン（SSAO）をマップに適用するか決定します。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "マウススクロール"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "フリー"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8方向"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "無効"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nマウスで画面移動をした時のカメラの挙動を設定します。"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nキーボードやマウスを使用しているときに、マップを画面移動する速度を設定します。"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nカメラの回転速度です。"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nカメラのズーム速度です。"
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "ズームの挙動"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "カーソルに呼応"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "カーソル位置にズームイン"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "カーソルを無視"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nズームイン・ズームアウト時のマウスカーソルに対するカメラの挙動を設定します。"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "コードエディタを開くコマンド"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "無効"
 SETTING_AUTOSAVE:0 "オートセーブ間隔"
 SETTINGS_FILE_TRANSFER_SPEED:0 "ファイル転送速度"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $ファイル転送速度$\n#!マルチプレイヤーロビーでのセーブゲームファイルの転送速度の上限を設定します。\n\n設定を低くすると、マルチプレイヤーゲームに参加するネットワークの安定性が向上する可能性がありますが、マルチプレイヤーの読み込み時間に悪影響を及ぼします。"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "マップエディタのオートセーブ(秒)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "マップエディタのオートセーブ間隔(秒)"
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "アクセシビリティ"
 SETTING_COLOR_BLIND_MODE:0 "色覚多様性モード"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!ゲーム中のテキストに使われている色を、色覚多様性に配慮した色へ変更します。"
 SETTING_TEXTURE_STREAMING:0 "テクスチャストリーミング"
 SETTING_TEXTURE_STREAMING_CACHE:0 "テクスチャストリーミングキャッシュサイズ"
 SETTING_VALUE_MB:0 "$VALUE$MB"
 SETTING_AUDIO_DEVICE_PROFILE:0 "オーディオプロファイル"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#! あなたの設定に合ったオーディオプロファイルを選択してください。"
 SETTING_AUDIO_OPTION_SPEAKERS:0 "スピーカー"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#! $SETTING_AUDIO_OPTION_SPEAKERS$のためのデフォルトのミックス"
 SETTING_AUDIO_OPTION_HEADPHONES:0 "ヘッドフォン"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#! $SETTING_AUDIO_OPTION_HEADPHONES$のためのミックス調整。"
 SETTING_AUDIO_OPTION_TV:0 "テレビ"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#! $SETTING_AUDIO_OPTION_TV$とモニタースピーカーのミックス。"
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "ナイトモード"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!夜間再生用に音を柔らかくし、高音域を暗くし、ダイナミックレンジを圧縮します。"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "ノードエディタ ドラッグ移動モード"
 SETTING_LENS_FLARE_TOOLTIP:0 "#T $SETTING_LENS_FLARE$\n#!ブルーム効果が非常に高い領域で現れるレンズフレア効果を有効にします。この効果の発現にはブルームを有効にしておく必要があります。\n\n無効化によりパフォーマンスが向上する場合があります。"
 SETTING_RENDERER_TOOLTIP:0 "どの描画エンジンが使用されているかを決定します。"
 SETTING_UPSCALE:0 "アップスケール方式"
 OPTION_UPSCALE_FSR2:0 "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS:0 "NVIDIA DLSS"
 OPTION_UPSCALE_XESS:0 "Intel® XeSS"
 SETTING_UPSCALE_QUALITY:0 "アップスケールクオリティ"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY:0 "ウルトラクオリティ"
 OPTION_UPSCALE_QUALITY_QUALITY:0 "クオリティ"
 OPTION_UPSCALE_QUALITY_BALANCED:0 "バランス"
 OPTION_UPSCALE_QUALITY_PERFORMANCE:0 "パフォーマンス"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE:0 "ウルトラパフォーマンス"
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP:0 "#T $SETTING_SECONDARY_LENS_FLARE$\n#!高度に咲く領域に現れる二次レンズフレア効果を可能にします。効果を有効にするためにはブルームを有効にする必要があります。\n\nオフにすると、パフォーマンスが向上する可能性があります。"
 SETTING_TEXTURE_STREAMING_TOOLTIP:0 "#T $SETTING_TEXTURE_STREAMING$#!\nテクスチャは必要に応じて読み込まれます。\n\nCPU時間のオーバーヘッドを犠牲にして、GPUメモリの使用量を削減します。少量のメモリでGPUのパフォーマンスが向上する可能性があります。"
 SETTING_VO:0 "ボイスオーバー"
 SETTING_VO_TOOLTIP:0 "#T ボイスオーバーの音量\n#! ゲーム内のボイスオーバーの音量を設定します。"
 SETTING_MUSIC_DENSITY:0 "音楽の頻度"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "歌、静かな曲、ムードミュージックの優先度のバランスを制御します。\n\n激しい=主に「ラジオ局」のような曲が次々に再生されます。\nバランスのとれた=歌、静かな曲、ムードミュージックの完璧なバランス\nリラックス=主にリラックスした音楽セグメントは、より良い気分体験を提供し、数時間演奏した後の繰り返し感が少ない"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE:0 "全自動モードのコンソール"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND:0 "全て開き、タブで選ぶ"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND:0 "違う部分だけ展開する"