l_english:
 SETTING_DEBUG_SAVES:0 "Number of debug saves"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "Disabled hints"
 SETTING_FOCUS_ON_COMBAT:0 "Focus on combat"
 SETTING_TOOLTIP_DELAY:1 "Tooltip Delay"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before tooltips appear."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 # Audio
 SETTING_Sound_Effects:1 "All Sound Effects"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Sound Effects Volume\n#!Sets the volume of ALL sound effects."
 SETTING_Ambience:0 "Ambience"
 SETTING_Ambience_TOOLTIP:1 "#T Ambience Volume\n#!Sets the volume of environmental ambience."
 SETTING_TOOLTIP_MODE:1 "Tooltip Mode"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nSets the way tooltips "lock in," enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Misc"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltips"
 SETTINGS_CATEGORY_SFX:0 "Specific Sound Effects"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "General"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Map Controls"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Save Games"
 SETTINGS_CATEGORY_LANGUAGE:0 "Language"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Advanced – General"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Advanced – Map"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Advanced – Characters"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Multiplayer"
 SETTINGS_CATEGORY_MAP:0 "Map"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Show graphic diseases and injuries"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nSets whether graphic injuries and diseases will be visible on character portraits."
 SETTING_SHOW_NUDITY:0 "Show nudity"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Royal Court Idle Pan"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermines if the camera in the Royal Court should pan gently across your Court when idle.\n\nIf Animated Characters is turned off, this setting has no effect."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Royal Court Smooth Transitions"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermines if the camera in the Royal Court should move smoothly to a new location.\n\nIf Animated Characters is turned off, this setting has no effect."
 NEVER:0 "Never"
 MONTHLY:0 "Every month"
 HALFYEAR:0 "Every 6 months"
 YEARLY:0 "Every year"
 FIVE_YEAR:0 "Every 5 years"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Show Reactive Advice"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nSets if the game should show tutorial Advice reacting to how you play. Useful for players new to Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Show Suggestions"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nSets if the game should suggest something to do at regular intervals. Useful for players new to Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Reset Reactive Advice"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Reset Reactive Advice#!\nPreviously seen Reactive Advice will show up once more."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Reset Reactive Advice"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Are you sure you want to Reset Reactive Advice?"
 SETTING_ADVANCED_SHADERS:0 "Advanced Shader Effects"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Advanced Shader Effects\n#!This option will enable advanced shader effects.\n\nTurning it off may increase performance at the cost of making some effects (e.g. terrain and water) look worse"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Winter Particle Effects"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermines whether particle effects are shown or not when Winter is active in some areas of the map.\n\nTurning it off may increase performance"
 SETTING_RESET_CAMERA_ROTATION:0 "Camera Rotation Reset"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the camera should automatically reset default position after being rotated by the user"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Court Scene Background Characters"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the Royal Court 3D scene should display less important background characters."
 SETTING_MAP_HIGHLIGHT:0 "Map Cursor Highlight"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermines the intensity of the cursor highlights on the map"
 BASED_ON_ZOOM_LEVEL:0 "Dynamic"
 ALWAYS_HIDE:0 "Always Hide"
 ALWAYS_SHOW:0 "Always Show"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Coastal Borders"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nThis option will control when coastal realm borders should be shown.\nIf $BASED_ON_ZOOM_LEVEL$ then they will be hidden in the detail zoom level.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."
 SETTINGS_DISCARD_CHANGES:0 "Discard Changes"
